name: on push
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
    paths-ignore:
      - README.md
      - .github/*
      - docs/*
env:
  GIT_USERNAME: '${{ github.actor }}'
  GIT_EMAIL: github-actions@github.com
  PA_TOKEN: '${{ secrets.GHA_PAT }}'
jobs:
  lint:
    permissions:
      contents: read
      id-token: write
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: false
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Test
        run: go test ./...
